### ISSUE TITLE
getCredentials() always redirects to getLoginUrl() on return early?

### ISSUE THREAD

**Issue by nesl247** [knpuniversity/guard-tutorial#4]
Since `getCredentials()` is called on every request, if you return early (because the path isn't `login_check`) like your example shows, does that mean it will always redirect to `getLoginUrl()` when in a secured section of a site?

How does it handle being authenticated already?

<img width="944" alt="screenshot 2015-07-16 11 11 37" src="https://cloud.githubusercontent.com/assets/1037526/8727025/78ae1eca-2bab-11e5-9c84-a694bfd1738f.png">

**Comment by nesl247** [comment]
I may be a bit confused because there isn't anything in the tutorial which truly describes the entire path of authentication when using Guard. It would be really helpful to have the first part of the tutorial describe the authenticator class itself, and how it progresses. From both an unauthenticated call to an authenticated area, to an authenticated call to an authenticated area, so that you can understand how it flows from one method to the next.

**Comment by weaverryan** [comment]
I see the problem with the `getCredentials()` description. Without saying anything else (and not speaking to your next comment yet), is this clear?

<img width="965" alt="screen shot 2015-07-16 at 12 45 44 pm" src="https://cloud.githubusercontent.com/assets/121003/8729337/9a859c00-2bb8-11e5-83da-876e067b0780.png">

About the flow through the Authenticator, this _is_ something that I want a developer to be able to understand. I'm going to add something next week - something visual :)

**Comment by nesl247** [comment]
Your changes definitely fix the issue.

**Comment by weaverryan** [comment]
Perfect - thanks for catching that

**Comment by nesl247** [comment]
Closing since this issue is actually fixed now. I'll create another issue for the flow as a request.
