### ISSUE TITLE
Clarify example 'checkCredentials()' - "doing nothing"

### ISSUE THREAD

**Issue by alister** [knpuniversity/guard-tutorial#6]
The first time around, this did confuse me a little, wondering why `checkCredentials()` was empty. 

Might it be a good idea to put a note (near the 'doing nothing' - or maybe in the code comments) to clarify that it has effectively already checked the credentials are good when it searched for the user by token, in `getUser()` ?

**Comment by weaverryan** [comment]
@alister Yep, I agree. I update the comment at sha: a326b83b22fcc1c6da3b2fdda75ead60b37c0c4f

If that's still not clear enough or you have a suggestion to improve further, let me know!

Thanks!
